package:
    name: pysdot
    version: 0.0.15

source:
    git_url: https://github.com/sd-ot/pysdot.git

build:
    number: 1000
    string: py{{PY_VER}}

requirements:
    host:
        - {{ compiler('cxx') }} # [win]
        - python {{PY_VER}}*
        - pybind11
        - cmake
        - boost
    run:
        - python {{PY_VER}}*
        - scipy 

about:
    home: https://github.com/sd-ot/pysdot
    license: MIT
    license_family: MIT
    summary: Semi-discrete Optimal Transportation tools
    description: |
        Tools for semi-discrete optimal transportation.
        Includes power diagram, integration on laguerre cells 
        for different densities and radial functions, ...
