package:
    name: pysdot
    version: 0.0.10

source:
    git_url: https://github.com/sd-ot/pysdot.git

build:
    number: 1000
    string: py{{PY_VER}}

requirements:
    build:
        - python {{PY_VER}}*
    #     - numpy {{numpy}}*
    run:
        - python {{PY_VER}}*
    #     - numpy {{numpy}}*

about:
    home: https://github.com/sd-ot/pysdot
    license: MIT
    license_family: MIT
    summary: Semi-discrete Optimal Transportation tools
    description: |
        Tools for semi-discrete optimal transportation.
        Includes power diagram, integration on laguerre cells 
        for different densities and radial functions, ...
